### ISSUE TITLE
configparser.NoSectionError: No section: 'buildozer'

### ISSUE THREAD

**Issue by Jalkhov** [ArtemSBulgakov/buildozer-action#11]
Hi, i am getting the following error triying to run a workflow manually

<details>
<summary>Log error</summary>

```
[25](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:25)
Traceback (most recent call last):
[26](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:26)
  File "/home/user/.local/bin/buildozer", line 8, in <module>
[27](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:27)
    sys.exit(main())
[28](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:28)
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/scripts/client.py", line 13, in main
[29](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:29)
    Buildozer().run_command(sys.argv[1:])
[30](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:30)
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1026, in run_command
[31](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:31)
    self.check_root()
[32](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:32)
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1053, in check_root
[33](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:33)
    warn_on_root = self.config.getdefault('buildozer', 'warn_on_root', '1')
[34](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:34)
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1207, in _get_config_default
[35](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:35)
    set_config_token_from_env(section, token, self.config)
[36](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:36)
  File "/home/user/.local/lib/python3.8/site-packages/buildozer/__init__.py", line 1265, in set_config_token_from_env
[37](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:37)
    config.set(section, token, env_var)
[38](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:38)
  File "/usr/lib/python3.8/configparser.py", line 1201, in set
[39](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:39)
    super().set(section, option, value)
[40](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:40)
  File "/usr/lib/python3.8/configparser.py", line 902, in set
[41](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:41)
    raise NoSectionError(section) from None
[42](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:42)
configparser.NoSectionError: No section: 'buildozer'
[43](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:43)
Traceback (most recent call last):
[44](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:44)
  File "/action/entrypoint.py", line 159, in <module>
[45](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:45)
    main()
[46](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:46)
  File "/action/entrypoint.py", line 27, in main
[47](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:47)
    run_command(env["INPUT_COMMAND"])
[48](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:48)
  File "/action/entrypoint.py", line 135, in run_command
[49](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:49)
    retcode = subprocess.check_call(command, shell=True)
[50](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:50)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
[51](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:51)
    raise CalledProcessError(retcode, cmd)
[52](https://github.com/Jalkhov/chichero/runs/5060474903?check_suite_focus=true#step:4:52)
subprocess.CalledProcessError: Command 'buildozer android debug' returned non-zero exit status 1.
```
</details>

<details>
<summary>The workflow file</summary>

```
name: Build
	on: workflow_dispatch
	
	jobs:
	  # Build job. Builds app for Android with Buildozer
	  build-android:
	    name: Build for Android
	    runs-on: ubuntu-latest
	
	    steps:
	      - name: Checkout
	        uses: actions/checkout@v2
	
	      - name: Build with Buildozer
	        uses: ArtemSBulgakov/buildozer-action@v1
	        id: buildozer
	        with:
	          workdir: elchichero
	          buildozer_version: stable
	
	      - name: Upload artifacts
	        uses: actions/upload-artifact@v2
	        with:
	          name: package
	          path: ${{ steps.buildozer.outputs.filename }}
```

</details>

EDIT: I can see in the [repo action](https://github.com/ArtemSBulgakov/buildozer-action/runs/5014973319?check_suite_focus=true#step:3:1717) exist a similar error.

**Comment by Jalkhov** [comment]
Ok, i have find the problem, my `.gitignore` was ignoring `buildozer.spec`.
