### ISSUE TITLE
I got # AIDL not found, please install it.

### ISSUE THREAD

**Issue by JVProdc** [ArtemSBulgakov/buildozer-action#31]
I got this error, but I don't know how to instal aidl, can anyone help me?

Traceback:

# Aidl not found, please install it.
Traceback (most recent call last):
  File "/action/entrypoint.py", line 159, in <module>
    main()
  File "/action/entrypoint.py", line 27, in main
    run_command(env["INPUT_COMMAND"])
  File "/action/entrypoint.py", line 135, in run_command
    retcode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'buildozer android debug' returned non-zero exit status 1.
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Build with Buildozer

**Comment by Thimphu123** [comment]
Same

**Comment by manatlan** [comment]
@Thimphu123 @JVProdc 
add this in your spec file :

`android.accept_sdk_license = True`

let me know, if this fix your problem

**Comment by JVProdc** [comment]
> @manatlan I switch to use python-for-android directly and it works

Ok, thank you

**Comment by kurdemol94** [comment]
if anyone still searching for a solution, adding `yes | ` in front of the command worked for me. Also used the latest version so not sure if it's relevant, I had the accept_sdk_license flag previously set to true and it didn't help

```
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozerBuild
        with:
          command: yes | buildozer -v android debug
          buildozer_version: master

**Comment by Novfensec** [comment]
# Problems solved!

@everyone
🎉 **Exciting News!** 🎉

I'm thrilled to announce that my **APK build process** for the [SAMPLE-KIVYMD-APP](https://github.com/Novfensec/SAMPLE-KIVYMD-APP) repository has been **successfully completed** on GitHub! 🚀

It took some frustrating build failures but still I managed to succeed.

After resolving several challenges, my GitHub Actions workflow now reliably builds the APK for my KivyMD application, thanks to the latest updates and optimizations. This achievement marks a significant milestone for my project, bringing us one step closer to delivering an enhanced mobile experience.

🔧 **Key Highlights:**
- **Automated APK Building**: Our workflow now efficiently handles the APK build process without manual intervention.
- **Optimized Dependencies**: We’ve integrated all necessary dependencies, ensuring a smooth build environment.
- **Seamless Deployment**: The build process is fully automated, making it easier to deploy updates and improvements.

For more details, you can check out the repository [here](https://github.com/Novfensec/SAMPLE-KIVYMD-APP). I am looking forward to your feedback.

Stay tuned for more updates and happy coding!

**Comment by ArtemSBulgakov** [comment]
Please try with the new version [v1.2.0](https://github.com/ArtemSBulgakov/buildozer-action/releases/tag/v1.2.0). Feel free to open a new issue if the problem still exists
